name: Generate Waves Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Waves Animation
        uses: platane/snk@v3
        with:
          github_user_name: c0mr4de-laugh4l0t
          outputs: |
            dist/waves.svg
            dist/waves-dark.svg?palette=github-dark

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
